# Generated by Django 5.2.1 on 2025-06-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_categorias_comentarios_publicaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='publicaciones.publicaciones'),
        ),
    ]
